.PHONY: run

1-linear-search:1-linear-search.o
1-linear-search.o:1-linear-search.c
	$(CC) -c $<

2-linear-search:2-linear-serach.o
2-linear-serach.o:2-linear-serach.c
	$(CC) -c $<

1:1-linear-search
	./$<

2:2-binary-search
	./$<
